[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/src',
    'solady/=lib/solady/',
    'seaport-types/=lib/seaport-types/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'solarray/=lib/solarray/src/',
    'openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/',
    'openzeppelin-contracts/contracts/token/=lib/openzeppelin-contracts/contracts/token/',
]
# bytecode_hash = 'none'
ignored_error_codes = ['license', 'code-size', 'init-code-size', 2519]
optimizer_runs = 99_999_999

[profile.lite.fuzz]
runs = 1

[profile.ffi]
ffi = true
test = 'test-ffi'
fs_permissions = [{ access = 'read-write', path = './test-ffi/' }]

# Use a very small number of default fuzz runs to speed up local testing. It is
# recommended to increase this number or use the `--fuzz-runs=256` flag to run
# a proper fuzzing campaign before yeeting your project to mainnet.
[profile.ffi.fuzz]
runs = 5

[profile.ci-ffi]
ffi = true
test = 'test-ffi'
fs_permissions = [{ access = 'read-write', path = './test-ffi/' }]

# Use a relatively small number of fuzz runs in CI because the ffi lifecycle is
# slow.
[profile.ci-ffi.fuzz]
runs = 10
